// <auto-generated />
namespace Persion_Assistant08.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class posit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(posit));
        
        string IMigrationMetadata.Id
        {
            get { return "201812111656096_posit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
